### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by ajakka** [mouaadblhn/controllet.js#1]
Are there any plans to add this library to the NPM repository?

**Comment by mouaadblhn** [comment]
Hi @ajakka,

I appreciate your suggestion about publishing the library to NPM. Currently, the primary focus is on improving the library for native JS developers. The library is designed to be easily included in projects by using the `controllet.min.js` file.

Once we've further stabilized the library for native JS usage, we'll certainly consider exploring options like publishing to NPM to make it accessible to a wider audience.

Thank you! I appreciate your feedback!
